import { formattedMaxDate, formattedMinDate } from "./constants";

export const loginFields = [
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "email-address",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];

export const reauthFields = [
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];

export const signUpFileds = [
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "email-address",
    name: "email",
    type: "email",
    // autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Username",
    labelFor: "username",
    id: "username",
    name: "username",
    type: "username",
    // autoComplete: "username",
    isRequired: true,
    placeholder: "Username",
  },
  {
    labelText: "Phone number",
    labelFor: "phone-number",
    id: "phone",
    name: "phone-number",
    type: "tel",
    autoComplete: "phone-number",
    isRequired: false,
    placeholder: "Phone number",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    // autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
  {
    labelText: "Confirm password",
    labelFor: "confirm-password",
    id: "confirm-password",
    name: "confirm-password",
    type: "password",
    // autoComplete: "current-password",
    isRequired: true,
    placeholder: "Confirm password",
  },
];

export const personalDetailsFields = [
  {
    labelText: "First Name",
    labelFor: "first-name",
    id: "firstName",
    name: "firstName",
    type: "text",
    // autoComplete: "given-name",
    isRequired: false,
    placeholder: "First Name",
  },
  {
    labelText: "Last Name",
    labelFor: "last-name",
    id: "lastName",
    name: "lastName",
    type: "text",
    // autoComplete: "family-name",
    isRequired: false,
    placeholder: "Last Name",
  },
  {
    labelText: "Occupation",
    labelFor: "occupation",
    id: "occupation",
    name: "occupation",
    type: "text",
    isRequired: false,
    placeholder: "Occupation",
  },
  {
    labelText: "Company",
    labelFor: "company",
    id: "company",
    name: "company",
    type: "text",
    isRequired: false,
    placeholder: "Company",
  },
  {
    labelText: "Region",
    labelFor: "region",
    id: "region",
    name: "region",
    type: "text",
    isRequired: false,
    placeholder: "Region",
  },
  {
    labelText: "Birthdate",
    labelFor: "birthdate",
    id: "birthdate",
    name: "birthdate",
    type: "date",
    isRequired: false,
    max: formattedMaxDate,
    min: formattedMinDate,
  },
];

export const otherProfilesFields = [
  {
    icon: "bi bi-facebook",
    labelFor: "facebook",
    id: "facebook",
    name: "facebook",
    type: "url",
    isRequired: false,
    placeholder: "Facebook Profile URL",
  },
  {
    icon: "bi bi-twitter",
    labelFor: "twitter",
    id: "twitter",
    name: "twitter",
    type: "url",
    isRequired: false,
    placeholder: "Twitter Profile URL",
  },
  {
    icon: "bi bi-linkedin",
    labelFor: "linkedin",
    id: "linkedin",
    name: "linkedin",
    type: "url",
    isRequired: false,
    placeholder: "LinkedIn Profile URL",
  },
  {
    icon: "bi bi-github",
    labelFor: "github",
    id: "github",
    name: "github",
    type: "url",
    isRequired: false,
    placeholder: "GitHub Profile URL",
  },
];

export const accountFields = [
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: false,
    placeholder: "Email address",
  },
  {
    labelText: "Phone number",
    labelFor: "phone-number",
    id: "phone",
    name: "phone-number",
    type: "tel",
    autoComplete: "phone-number",
    isRequired: false,
    placeholder: "Phone number",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];
